shifumi = {0: "\N{Raised Fist}", 1: "\N{Raised Hand}", 2: "\N{Victory Hand}", 3: "\N{OK Hand Sign}"}

alphabet = ['\N{REGIONAL INDICATOR SYMBOL LETTER A}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER B}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER C}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER D}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER E}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER F}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER G}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER H}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER I}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER J}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER K}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER L}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER M}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER N}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER O}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER P}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER Q}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER R}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER S}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER T}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER U}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER V}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER W}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER X}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER Y}',
        '\N{REGIONAL INDICATOR SYMBOL LETTER Z}']

pepeangry = [ "pepeangry", 702518264332550156 ]
pepecry = [ "pepecry", 702443746049916958 ]
pepedegenere = [ "pepedegenere", 702518959223603220 ]
pepelove = [ "pepelove", 706872631252615228 ]
zoglu = [ "zoglu", 789166303062523963 ]
zoglon = [ "zoglon", 723694983382695936 ]


love = ['\N{SPARKLING HEART}',
        '\N{REVOLVING HEARTS}',
        '\N{GROWING HEART}',
        '\N{BEATING HEART}',
        '\N{TWO HEARTS}',
        '\N{HEART WITH ARROW}',
        '\N{HEART WITH RIBBON}',
        '\N{ORANGE HEART}',
        '\N{HEAVY BLACK HEART}',
        '\N{BLUE HEART}',
        '\N{YELLOW HEART}',
        '\N{GREEN HEART}',
        '\N{BLUE HEART}',
        '\N{SMILING FACE WITH HEART-SHAPED EYES}',
        '\N{SMILING FACE WITH SMILING EYES AND THREE HEARTS}']


